name: firebase_functions_interop_test
description: Test Firebase Functions Interop
version: 0.0.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  firebase_functions_interop:
    path: ../

dev_dependencies:
  build_runner: 1.11.5
  build_node_compilers:
    git:
      url: git://github.com/Semapl3/node-interop
      path: build_node_compilers
