name: firebase_functions_interop
description: Firebase Cloud Functions SDK for Dart written as a JS interop wrapper for official Node.js SDK.
version: 1.0.4
homepage: https://www.github.com/pulyaevskiy/firebase-functions-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  js: ^0.6.2
  meta: 1.2.3
  node_interop:
    git:
      url: git://github.com/Semapl3/node-interop
      path: node_interop
  node_io:
    git:
      url: git://github.com/Semapl3/node-interop
      path: node_io
  node_http:
    git:
      url: git://github.com/Semapl3/node-interop
      path: node_http
  firebase_admin_interop:
    git:
      url: git://github.com/Semapl3/firebase-admin-interop

dev_dependencies:
  test: ^1.15.7
